version: "3.9"

x-config: &default-config
  labels:
    - "traefik.docker.network=traefik"
  networks:
    - traefik

services:
  app:
    <<: *default-config
    image: user-gallery-app:2.7.6
    tty: true
    stdin_open: true
    build: .
    container_name: user-gallery-app
    env_file:
      - .env.development
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/user-gallery
      - ./Gemfile:/user-gallery/Gemfile
      - ./Gemfile.lock:/user-gallery/Gemfile.lock
      - bundle:/user-gallery/bundle
    ports:
      - 3006:3000
    depends_on:
      - postgres
  
  postgres:
    <<: *default-config
    image: postgres:14.2
    container_name: user-gallery-db
    env_file:
      - .env.development
    ports:
      - 5435:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  bundle:
  postgres_data:

networks:
  traefik:
    name: traefik_webgateway